hlg:
  parceiros_v3:
    wsdl:
    endpoint:
  parceiros_v3_ssl:
    wsdl:

stg:
  parceiros_v3:
    wsdl:
    endpoint:
  parceiros_v3_ssl:
    wsdl:

prd:
  parceiros_v3:
    wsdl:
    endpoint:
  parceiros_v3_ssl:
    wsdl:
